### ISSUE TITLE
你好，这个computed扩展能用在page上吗

### ISSUE THREAD

**Issue by wishinlife** [wechat-miniprogram/computed#1]
你好，这个扩展很好，很多时候很需要计算属性，但在page上又办法引用这个扩展吗？

**Comment by JuneAndGreen** [comment]
可以的，用 Component 构造器来构造页面即可使用这个扩展。

可以参考官方文档：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html#%E4%BD%BF%E7%94%A8-component-%E6%9E%84%E9%80%A0%E5%99%A8%E6%9E%84%E9%80%A0%E9%A1%B5%E9%9D%A2
