### ISSUE TITLE
XX is not found

### ISSUE THREAD

**Issue by dagang007** [wechat-miniprogram/computed#10]
demo 导入项目，根本打不开！！！！！！！！！！

**Comment by JuneAndGreen** [comment]
你怎么导入的，如果是直接使用 tools/demo 是不行的，要先进行 npm run dev 生成 miniprogram_dev 后将此目录作为 demo 导入。具体可以看下 [miniprogram-custom-component](https://github.com/wechat-miniprogram/miniprogram-custom-component) 的说明。

如果还有问题，麻烦贴下报错截图。
