### ISSUE TITLE
v5.0.0，computed计算properties时没有更新

### ISSUE THREAD

**Issue by shadow-dust** [wechat-miniprogram/computed#101]
页面在onLoad调取接口获取数据，传值给组件，组件使用computed计算，只计算了第一次传入null的时候，后面接口返回获取值后，没有重新计算，在页面是可以直接显示出传入的值的
![微信截图_20240920171610](https://github.com/user-attachments/assets/78eec8bd-347e-47b4-aba2-4ad9f4100406)
![微信截图_20240920171542](https://github.com/user-attachments/assets/ef2b9f85-76e7-4741-b4e0-3892cb7cc3f4)
![微信截图_20240920171548](https://github.com/user-attachments/assets/3ad437ff-b9b2-4caf-b2d5-b2ef9d7b9039)
![微信截图_20240920171557](https://github.com/user-attachments/assets/98c2bb60-e4b4-42c9-b84d-ef0966e8307d)

**Comment by LastLeaf** [comment]
看的不是很明白。有完整点的例子吗？
