### ISSUE TITLE
@types/wechat-miniprogram 还在 dependencies 中导致跟项目中已安装的类型冲突

### ISSUE THREAD

**Issue by liuweiGL** [wechat-miniprogram/computed#102]
https://github.com/wechat-miniprogram/computed/issues/65

https://github.com/wechat-miniprogram/computed/blob/1199d6ac1d269d45b204fcb9c58cbf1376e437f3/package.json#L67

现在官方文档用的是 https://github.com/wechat-miniprogram/api-typings

**Comment by LastLeaf** [comment]
升级到 miniprogram-api-typings v4 有点问题。暂时先用 v3 。

**Comment by LastLeaf** [comment]
已发布 5.1.0 来更新这里。
