### ISSUE TITLE
can't call setData in computed getter function!

### ISSUE THREAD

**Issue by yhhwpp** [wechat-miniprogram/computed#11]
在开发者工具报`can't call setData in computed getter function!` 提示，请问是什么原因。
代码片段  https://developers.weixin.qq.com/s/zkJXLjmY7w5J
![image](https://user-images.githubusercontent.com/7929656/50957836-3419db00-14fa-11e9-9be0-d731d596353f.png)

**Comment by JuneAndGreen** [comment]
这个是 setData 修改 props，触发了 props 的监听器引起的，是一个 bug，后续我修一下。

**Comment by JuneAndGreen** [comment]
0.0.7 版本 fixed
