### ISSUE TITLE
请问 小程序基础库 2.2.3 以下版本能实现兼容吗

### ISSUE THREAD

**Issue by GuoYiJi** [wechat-miniprogram/computed#12]
目前在低版本下面computed计算出来的属性会被忽略，造成部分功能无法正常使用

**Comment by JuneAndGreen** [comment]
使用了 definitionFilter 这个特性实现的：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/extend.html

目前无法向下兼容。
