### ISSUE TITLE
版本：0.0.7重现 can't call setData in computed getter function!

### ISSUE THREAD

**Issue by Josie-ljw** [wechat-miniprogram/computed#14]
![image](https://user-images.githubusercontent.com/20377604/55701469-d49e6f00-5a05-11e9-9c29-809b8cc7e121.png)
你好，我在0.0.7版本上重现了这个问题，只要在computed里面setData就会报错诶，可以帮我看看什么问题么？

**Comment by JuneAndGreen** [comment]
当前的实现不允许在 computed 字段的 getter 函数中调用 setData，不然很容易引起数据紊乱。
