### ISSUE TITLE
新版本无法使用westore了

### ISSUE THREAD

**Issue by borie88** [wechat-miniprogram/computed#15]
1.0.0版以下同一个自定义组件可以使用store和computed，computed可以监听store注入的data。2.0.x版本莫名其妙地不会监听store注入的data，也会让westore的this.update函数报错。希望可以兼容更多的主流开发环境

**Comment by LastLeaf** [comment]
2.0.x 实现的原理完全不一样了。有其他库不兼容也是正常的。

需要一点时间针对性分析后看看怎么修复。

**Comment by LastLeaf** [comment]
@borie88 我用 westore 自带的例子试了下看样子没啥问题。我对它不熟悉，能给个你的案例吗？

**Comment by TtTRz** [comment]
暂时关闭此 Issue，如有相关疑问，请提供可稳定复现问题的 DEMO（小程序代码片段）再重新打开此 Issue。
