### ISSUE TITLE
dataTracer.create方法会把数组对象都转成对象

### ISSUE THREAD

**Issue by chentao106** [wechat-miniprogram/computed#16]
dataTracer.create方法会把数组对象都转成对象，这样导致计算属性里面，原本的数组都不能按数组逻辑来处理了

**Comment by LastLeaf** [comment]
get 之后补一下数组的读方法。

**Comment by LastLeaf** [comment]
已修复在 2.0.2 。

数组的“读”方法有效了。

**Comment by jhxxs** [comment]
小白表示没看懂，在计算属性里，通过data获取到的数据还是`Object`
