### ISSUE TITLE
第二次进入时computed属性无效

### ISSUE THREAD

**Issue by wishinlife** [wechat-miniprogram/computed#2]
在含有computed计算属性的页面，第一次进入时都正常计算，如果马上返回，再次进入时，计算属性就无法计算，发现是behavis里的computedCache里缓存了在第一次打开页面时的computed属性值，但第二次进入时，页面的data会初始化，页面上的computed是没有值的，因此造成第二次及之后打开此页面computed属性无效的问题。

**Comment by JuneAndGreen** [comment]
@wishinlife 可以确认下是否是和 #3 同一个问题？该问题在 0.0.5 尝试修复了。

**Comment by wishinlife** [comment]
> @wishinlife 可以确认下是否是和 #3 同一个问题？该问题在 0.0.5 尝试修复了。

在0.0.5中已修复此问题，确认与#3是同一个问题，在0.0.5前，只要有一个页面存在computed属性，进入后马上返回，再次进入，我多次测试，在第三次进入时，computed值就没有了，使用0.0.5后，问题解决。
