### ISSUE TITLE
v2.0.2 如果 `data` 中的值是 `object`，`computed` 中的方法，无法获取该值（返回该值为`{}`）

### ISSUE THREAD

**Issue by movii** [wechat-miniprogram/computed#20]
如果 `data` 的一个值是 `object`,  从 `computed` 中定义的方法，传入的 data 获取该值，一直为 `{}`。比如下面这样的例子：

`data` 中有一个 `child`：
```javasctipt
data: {
  child: {
    key: value
  }
}
```

在 `computed` 方法中想要获取 `data.child`，只会得到 `{}`

```javascript
computed: {
  computedChild (data) {
    console.info(data.child)
    return data.child
  }
}
```

---

用 README 里提供的代码片段做了简单修改跑了下（定义了 `data.c`，尝试从 `computed` 的函数中获取该 `data.c`），如图 `console` 返回 `{}`。

<img width="941" alt="Screenshot 2019-09-11 16 33 17" src="https://user-images.githubusercontent.com/4216619/64681957-35e5d500-d4b3-11e9-9f98-d10f75d7ab3b.png">

**Comment by LastLeaf** [comment]
data.child 是一个类似于 proxy 的特殊对象。这里需要加工一下让它最终返回普通对象。

**Comment by LastLeaf** [comment]
Published in v2.0.3
