### ISSUE TITLE
初始时会报错, Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by zhifengjiang** [wechat-miniprogram/computed#24]
oldVal为undefined
![image](https://user-images.githubusercontent.com/6251979/67256096-01a10380-f4b8-11e9-9d44-235d53a5c812.png)

**Comment by LastLeaf** [comment]
看截图上面 L295 oldVal 是有的。

麻烦提供下出问题的用例。

**Comment by TtTRz** [comment]
暂时关闭此 Issue，如有相关疑问，请提供可稳定复现问题的 DEMO（小程序代码片段）再重新打开此 Issue。
