### ISSUE TITLE
针对数组的遍历

### ISSUE THREAD

**Issue by renqiankun** [wechat-miniprogram/computed#25]

**Comment by LastLeaf** [comment]
computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？

**Comment by renqiankun** [comment]
computed 里面数据涉及对data中数组遍历时 forEach &nbsp;或 for in &nbsp;都无法遍历




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 凌晨0:19
收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;;
抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25)




computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？

**Comment by LastLeaf** [comment]
> computed 里面数据涉及对data中数组遍历时 forEach &nbsp;或 for in &nbsp;都无法遍历
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 凌晨0:19 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我用最新版试了下看起来没问题。你使用的是哪个版本呢？

**Comment by renqiankun** [comment]
不好意思啊 直接使用的官网的例子不可以， 重新安装后需要一个rfdc文件，就可以了。 添麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午2:14
收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;;
抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25)



 
computed 里面数据涉及对data中数组遍历时 forEach &nbsp;或 for in &nbsp;都无法遍历
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 凌晨0:19 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我用最新版试了下看起来没问题。你使用的是哪个版本呢？

**Comment by LastLeaf** [comment]
> 
> 不好意思啊 直接使用的官网的例子不可以， 重新安装后需要一个rfdc文件，就可以了。 添麻烦了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月6日(星期三) 下午2:14 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面数据涉及对data中数组遍历时 forEach &nbsp;或 for in &nbsp;都无法遍历 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 凌晨0:19 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我用最新版试了下看起来没问题。你使用的是哪个版本呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

示例里面的代码片段吗？

**Comment by renqiankun** [comment]
https://github.com/wechat-miniprogram/computed&nbsp; 里面有一个示例地址https://developers.weixin.qq.com/s/kKu4U9mX78a8&nbsp;直接在这个基础上修改的，这个示例针对数组以外的可以，但是数组不可以遍历， 是不是可以考虑把这个示例换成一个完整的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 凌晨0:45
收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;;
抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25)



 
不好意思啊 直接使用的官网的例子不可以， 重新安装后需要一个rfdc文件，就可以了。 添麻烦了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月6日(星期三) 下午2:14 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面数据涉及对data中数组遍历时 forEach &nbsp;或 for in &nbsp;都无法遍历 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LastLeaf"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 凌晨0:19 收件人:&nbsp;"wechat-miniprogram/computed"<computed@noreply.github.com&gt;; 抄送:&nbsp;"［重-要-邮-件］-WEM"<526472759@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wechat-miniprogram/computed] 针对数组的遍历 (#25) computed 里面会给数组加一层代理，和普通数组有点不一样。具体什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我用最新版试了下看起来没问题。你使用的是哪个版本呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
示例里面的代码片段吗？

**Comment by LastLeaf** [comment]
这个例子里面使用的版本比较老。我更新了一下。
