### ISSUE TITLE
如何支持在 Page 中的 computed？

### ISSUE THREAD

**Issue by luckymore** [wechat-miniprogram/computed#29]

**Comment by LastLeaf** [comment]
[使用 Component 构造器构造页面](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#%E4%BD%BF%E7%94%A8-Component-%E6%9E%84%E9%80%A0%E5%99%A8%E6%9E%84%E9%80%A0%E9%A1%B5%E9%9D%A2)

或者用 2.9.2 的新特性：[在 Page 中使用 behaviors](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#%E5%9C%A8%E9%A1%B5%E9%9D%A2%E4%B8%AD%E4%BD%BF%E7%94%A8-behaviors)
