### ISSUE TITLE
企业微信不支持么

### ISSUE THREAD

**Issue by shenjiuer** [wechat-miniprogram/computed#31]
`watch` 和 `computed` 都无效

**Comment by MuLoo** [comment]
> `watch` 和 `computed` 都无效

你可能是在page里用behaviors的方式引用的computed，这种情况下企业微信里确实无法触发computed，建议使用Components来构造页面即可。

[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html#%E4%BD%BF%E7%94%A8-component-%E6%9E%84%E9%80%A0%E5%99%A8%E6%9E%84%E9%80%A0%E9%A1%B5%E9%9D%A2)

**Comment by LastLeaf** [comment]
企业微信带的基础库比微信要稍微老一些，所以请注意有关版本兼容性的说明
