### ISSUE TITLE
可以直接从uni-app vue转换吗？

### ISSUE THREAD

**Issue by RayJason** [wechat-miniprogram/computed#32]
在VUE使用了computed，通过v-bind:style使用在H5有效，在微信开发工具无效

**Comment by LastLeaf** [comment]
请注意接口的差异。

有一个很大的区别是这里 computed 有参数 `data` ，computed 计算值必须只源于这个 data 。

**Comment by RayJason** [comment]
> 请注意接口的差异。
> 
> 
> 
> 有一个很大的区别是这里 computed 有参数 `data` ，computed 计算值必须只源于这个 data 。

后来同学研究了一下解决了，在data初始化使用，谢谢！
