### ISSUE TITLE
behavior 嵌套使用时 computed data 不会在初始视图中渲染

### ISSUE THREAD

**Issue by ItsRyanWu** [wechat-miniprogram/computed#37]
自定义 behavior A 使用 computed behavior 后，page/component 再使用该 behavior A，computed data 不会在视图中渲染,

但是可以在 instance.data 里找到该 computed data, 也可以在 onReady 等方法中 log 出该 data

目前我自己试出来的指标不治本的解决方案有两个

1. 声明一个和 computed data 同 key name 的 data 在 behavior A 中

2.在 behavior A 中的 onReady 方法里 `this.setData({computedDataA: this.data.computedDataA})`

**Comment by LastLeaf** [comment]
与 #35 类似。需要大更新解决。

**Comment by TtTRz** [comment]
3.0.0 版本支持该特性。

**Comment by ItsRyanWu** [comment]
> 3.0.0 版本支持该特性。

请您更新一下 npm 上的源码版本

**Comment by TtTRz** [comment]
> > 3.0.0 版本支持该特性。
> 
> @TtTRz @LastLeaf 请您更新一下 npm 上的源码版本

npm 上的可能会稍晚点同步，还需要观察一段时间。
如果你急用的话，可以先手动编译用着这里的版本。
如果在使用期间有任何问题的话，欢迎在这个 issue 或者开个新的提出，我们会继续跟进。

**Comment by deqwin** [comment]
+1，希望尽快支持，很急需

**Comment by LastLeaf** [comment]
3.x 已经支持。

**Comment by ibullet-chzn** [comment]
初始视图渲染完，后续不再更新了么？
