### ISSUE TITLE
为什么2.0版本会影响 Array.isArray的判断？

### ISSUE THREAD

**Issue by asmallkite** [wechat-miniprogram/computed#38]
发现升级了新版本之后，原本Array.isArray的功能都不正常了。

**Comment by LastLeaf** [comment]
现在是使用了一个类似于“proxy”的机制实现的， Array.isArray 无法兼容于这种 proxy 。可以考虑改用 instanceof 。

**Comment by TtTRz** [comment]
如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
