### ISSUE TITLE
关于纯数据字段的处理

### ISSUE THREAD

**Issue by EthanZhong** [wechat-miniprogram/computed#39]
开发过程种发现computed可以根据纯数据字段计算出值，而watch则不能监测纯数据字段的变化。

**Comment by TtTRz** [comment]
麻烦提供下能复现此问题的代码片段

**Comment by TtTRz** [comment]
暂时关闭此 Issue，如有相关疑问，请提供可稳定复现问题的 DEMO（小程序代码片段）再重新打开此 Issue。
