### ISSUE TITLE
使用miniprogram-computed组件后，小程序 observers 无法使用通配符 **

### ISSUE THREAD

**Issue by waiwing** [wechat-miniprogram/computed#42]
observers: {
    "**":function(){
    //使用 setData 后不会被触发     
    }
}

**Comment by LastLeaf** [comment]
请问用的是哪个版本的？

**Comment by waiwing** [comment]
"version": "2.1.1"

**Comment by waiwing** [comment]
> 请问用的是哪个版本的？

"version": "2.1.1"

**Comment by LastLeaf** [comment]
Fixed in v2.2.0 and v3.1.0
