### ISSUE TITLE
mobx store里的数组数据不能用于computed? 初始化也取不到mobx数据

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/computed#43]
我发错repo了, 在这里重发一遍
复现例子:
https://developers.weixin.qq.com/s/hgT6RCmL7Fkm

`accounts`是store里的一个数组
```
export const store = observable({

  // 数据字段
  numA: 4,
  numB: 5,
  accounts: [4, 5, 6],

  add: action(function() {
    this.accounts = [1, 2, 3]
  }),

  // actions
  update: action(function () {
    this.numA = this.numA + 1
    this.numB = this.numA + 1
  })

})
```

当启动的时候, 会报一个bug说
```
VM824:1 MiniProgramError
data.accounts.reduce is not a function
TypeError: data.accounts.reduce is not a function
    at sum (http://127.0.0.1:63254/appservice/index/components/computed-example.js:17:28)
    at http://127.0.0.1:63254/appservice/components/index.js:392:21
    at Array.forEach (<anonymous>)
    at Ge.created (http://127.0.0.1:63254/appservice/components/index.js:385:34)
    at r.safeCallback (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1775504)
    at r.call (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1775397)
    at Function.M._advancedCreate (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1823182)
    at r.createComponent (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1834383)
    at e (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1919566)
    at e (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1920093)
```

```
Component({
  behaviors: [behaviorTest, storeBindingsBehavior, computedBehavior],
  computed: {
    sum(data) {
      console.log(data.accounts)
      return data.accounts.reduce((s, o) => s + o, 0)
    },
  },
  data: {
    a: 1,
    b: 1,
  },
  storeBindings: {
    store,
    fields: ['numA', 'numB','accounts'],
    actions: {
      buttonTap: 'add'
    },
  },

  methods: {
    onTap() {
      console.log(this.data.accounts[0], this.data.accounts.reduce((s, o) => s + o, 0))
      this.buttonTap()
    }
  }
})
```

**Comment by chenzhutian** [comment]
附一点debug的结果, 貌似调用mobx的array的函数(比如`reduce`)的时候, 会给path里面塞很多无关的东西?
![image](https://user-images.githubusercontent.com/3315274/94336297-a86d1880-0014-11eb-8eb5-9d1badf51816.png)

**Comment by chenzhutian** [comment]
我整了一个解决方法是把 `scheduleSetData` 这里的`value`全部用 mobx.toJS 转回普通js变量然后再set data
https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/blob/master/src/index.js#L66

另外 这里(https://github.com/wechat-miniprogram/computed/blob/master/src/data-tracer.js#L12) 的 `__wxValue__` value也会导致bug, 如果原来有一个key的值就是undefined的话,  这里的`__wxValue__`会导致 changed这里 (https://github.com/wechat-miniprogram/computed/blob/master/src/behavior.js#L165) 死循环.

其实我没太懂__wxValue__这个操作的意义, 我假设这是为了mark一下key不存在的情况. 为了区分 key不存在 和key值为undefined, 目前我的改法是 `const value = key in data ? data[key] : { __wxValue__: undefined }`.
上面的 (https://github.com/wechat-miniprogram/computed/blob/master/src/data-tracer.js#L4) ` if ('__wxValue__' in data) {
    return {}
  }` 我也改成了` if ('__wxValue__' in data) {
    return undefined
  }` . 否则的话输入一个不存在的key也会返回一个空object

**Comment by chenzhutian** [comment]
另外还有一个bug, computed 依赖的数据路径追踪初始化操作在组件的created阶段, 但是mobx binding的操作在attached阶段, 于是导致computed在初始化的时候拿不到mobx的数据

**Comment by LastLeaf** [comment]
> 
> 
> 我整了一个解决方法是把 `scheduleSetData` 这里的`value`全部用 mobx.toJS 转回普通js变量然后再set data
> https://github.com/wechat-miniprogram/mobx-miniprogram-bindings/blob/master/src/index.js#L66
> 
> 另外 这里(https://github.com/wechat-miniprogram/computed/blob/master/src/data-tracer.js#L12) 的 `__wxValue__` value也会导致bug, 如果原来有一个key的值就是undefined的话, 这里的`__wxValue__`会导致 changed这里 (https://github.com/wechat-miniprogram/computed/blob/master/src/behavior.js#L165) 死循环.
> 
> 其实我没太懂__wxValue__这个操作的意义, 我假设这是为了mark一下key不存在的情况. 为了区分 key不存在 和key值为undefined, 目前我的改法是 `const value = key in data ? data[key] : { __wxValue__: undefined }`.
> 这里 (https://github.com/wechat-miniprogram/computed/blob/master/src/data-tracer.js#L4) ` if ('__wxValue__' in data) { return {} }` 我也改成了` if ('__wxValue__' in data) { return undefined }` . 否则的话输入一个不存在的key也会返回一个空object

应该是和 computed 里面的数据代理处理方式有关。 toJS 可以规避掉一些这类问题。

`__wxValue__` 怀疑是触发了小程序基础库内的 bug 。

**Comment by LastLeaf** [comment]
请问是使用了哪个版本的 computed 和 mobx binding ？

**Comment by LastLeaf** [comment]
Fixed in v3.1.0
