### ISSUE TITLE
同一个组件引用俩个Behavior，如果俩个Behavior都是用了computed，会覆盖？

### ISSUE THREAD

**Issue by ibullet-chzn** [wechat-miniprogram/computed#45]
如题，并且如果当前组件使用了computed，Behavior里使用的computed也同样会被覆盖？

**Comment by LastLeaf** [comment]
核心问题是 `_computedWatchInfo` 对象会被挂在组件 this 下（这个 this 是整个组件共享的）。如果有多个 behavior 在同时引用 computed ，要设法使它们使用 `_computedWatchInfo` 字段时不会冲突。这个问题略复杂所以之前并没有实现。

**Comment by LastLeaf** [comment]
使用了新的方式来实现，现在应该没问题了。
