### ISSUE TITLE
在测试用例中, 为什么预期computed运行了两次?

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/computed#47]
具体是这个用例:
https://github.com/wechat-miniprogram/computed/blob/master/test/index.test.js#L323

这里预期 `expect(func2TriggeringCount).toBe(2)`, 请问是为什呢? 我自己看的话总感觉`d`只被算了一次
我自己用ts实现了一遍, 现在在补测试用例, 这个用例一直返回只算了一次
谢谢

```js
test('computed chains', () => {
  let func1TriggeringCount = 0
  let func2TriggeringCount = 0
  const componentId = _.load({
    template: '<view>{{a}}+{{b}}={{c}}, {{a}}+{{c}}={{d}}</view>',
    behaviors: [computedBehavior],
    data: {
      a: 1,
      b: 2,
    },
    computed: {
      c(data) {
        func1TriggeringCount++
        return data.a + data.b
      },
      d(data) {
        func2TriggeringCount++
        return data.a + data.c
      }
    }
  })
  const component = _.render(componentId)
  component.triggerLifeTime('attached')
  expect(_.match(component.dom, '<wx-view>1+2=3, 1+3=4</wx-view>')).toBe(true)
  expect(func1TriggeringCount).toBe(1)
  expect(func2TriggeringCount).toBe(2)

  ...
})
```

**Comment by chenzhutian** [comment]
我估计是因为这里重置了这个data object? 
https://github.com/wechat-miniprogram/computed/blob/master/src/behavior.js#L22

我记得原来的代码是
```js
  if (!this.data) {
        this.data = {}
   }
...

this.setData(this.data)
```
请问为啥更新之后需要每次都重置新的data object呢?  `const setDataObj = {}`

**Comment by chenzhutian** [comment]
最后发现是因为删掉了这两句
```
const { path: targetPath } = dataPath.parseSingleDataPath(targetField)
setDataOnPath(this.data, targetPath, dataTracer.unwrap(val))
```

原来有这两句, 在这个commit (https://github.com/wechat-miniprogram/computed/commit/9b853a8f564f43083f1d5a7f4dd282daccc5851a)之后删了, 为什呢?

**Comment by chenzhutian** [comment]
另外我看原来是
```
if (!this.data) {
  this.data = {}
}
...

this.setDate(this.data)
```
后来在 9b853a8 改用了 `const setDataObj = {}` 和 `this.setData(setDataObj)`
这是为啥呢? 谢谢

**Comment by LastLeaf** [comment]
最近几个版本运行原理大改过。现在的执行时机：

* attached 期间无条件调用每个 computed 函数（计算初始值），这次执行完成后会无条件触发一次 setData 用于应用计算结果（为了 batching ，这里只做一次 setData ）；
* 每次 setData 时调用有依赖项变更的 computed 函数。

这个是当前我们认为比较合适的实现方式。（你要模仿实现的话可以选别的时机，不过请考虑清楚。）

对这个 test case ，上述两个条件各命中一次，所以是两次。

**Comment by chenzhutian** [comment]
我理解一下, 按照这样的逻辑, 对于d, 现在的流程是这样的, 
 - attached的时候运算d, 然后不会去运算依赖项c, 而是直接给undefined
 - 渲染的时候再算一遍, 因为此时依赖项c以及更新了

这样好像合理一点, 因为created的时候依赖关系还没建立起来

这是test case
```js
    const componentId = _.load({
      template: '<view>{{a}}+{{b}}={{c}}, {{a}}+{{c}}={{d}}</view>',
      behaviors: [computedBehavior],
      data: {
        a: 1,
        b: 2,
      },
      computed: {
        c(data) {
          func1TriggeringCount++
          return data.a + data.b
        },
        d(data) {
          func2TriggeringCount++
          return data.a + data.c
        }
      }
    })
``
