### ISSUE TITLE
对性能影响大吗？

### ISSUE THREAD

**Issue by NathanHan1** [wechat-miniprogram/computed#49]
大概问一下，computed，对性能影响大吗，有做对应的实验验证吗？

**Comment by LastLeaf** [comment]
可以观察到有（相对于直接使用 observers ），但是具体算不算大，好像没有很合理的评价标准。

**Comment by TtTRz** [comment]
如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
