### ISSUE TITLE
computed中如何获取properties的值

### ISSUE THREAD

**Issue by junhaotong** [wechat-miniprogram/computed#5]
在某些场景下，可能需要computed组件传入properties的值

**Comment by junhaotong** [comment]
或者说这个computed包并不适用组件的properties 变更，只能使用properties的observer？

**Comment by yezongyang** [comment]
> 或者说这个computed包并不适用组件的properties 变更，只能使用properties的observer？

看了下源码， 好像只是对data数据做了代理处理

**Comment by JuneAndGreen** [comment]
当前的 computed 只是劫持了 setData，所以没有支持组件外传入的 property 变更，可以使用 property 的 observer 来实现。

后续我们支持一下 property 的变更。

**Comment by JuneAndGreen** [comment]
@junhaotong  `0.0.6` 版本已支持 properties。

**Comment by dogodo-cc** [comment]
> @junhaotong `0.0.6` 版本已支持 properties。

我目前在自定义组件的computed 使用properties 的值还是undefined，我传入data进去，打印出来是空对象
`// components/m-icon/m-icon.js
const computedBehavior = require('miniprogram-computed');
Component({
  behaviors: [computedBehavior],
  data: {
    a:1,
    b:2
  },
  properties: {
    icon: {
      type: String,
      value: ""
    },
    color: {
      type: String,
      value: "#fff"
    },
    fontSize: {
      type: String,
      value: "40rpx"
    }
  },
  computed: {
    style(data) {
      console.log(data)
      return `color: ${data.color};font-size:${data.fontSize}`
    }
  },
  lifetimes: {
    attached() {
      console.log(this.data)
    }
  }
})
`

**Comment by LastLeaf** [comment]
> 
> 
> > @junhaotong `0.0.6` 版本已支持 properties。
> 
> 我目前在自定义组件的computed 使用properties 的值还是undefined，我传入data进去，打印出来是空对象
> `// components/m-icon/m-icon.js const computedBehavior = require('miniprogram-computed'); Component({ behaviors: [computedBehavior], data: { a:1, b:2 }, properties: { icon: { type: String, value: "" }, color: { type: String, value: "#fff" }, fontSize: { type: String, value: "40rpx" } }, computed: { style(data) { console.log(data) return `color: ${data.color};font-size:${data.fontSize}`} }, lifetimes: { attached() { console.log(this.data) } } })`

v2.0.0 有点问题，我修复一下。

**Comment by LastLeaf** [comment]
在 2.0.1 修复了。
