### ISSUE TITLE
数组变成对象的bug

### ISSUE THREAD

**Issue by questionlin** [wechat-miniprogram/computed#51]
data:{
  a:[{...},{...},{...}]
},
computed:{
  b(data){
    return data.a
  }
}

这里的b会变成{0:{...},1:{...},2:{...}}

**Comment by LastLeaf** [comment]
发现问题了。有两个位置漏了 `dataTracer.unwrap` 调用：

https://github.com/wechat-miniprogram/computed/blob/master/src/behavior.js#L31

https://github.com/wechat-miniprogram/computed/blob/master/src/behavior.js#L48

**Comment by LastLeaf** [comment]
在 v3 版本以上实际上它是一个 proxy 对象。会在 v4.0.0 以上修复（补上 unwrap ）。

**Comment by LastLeaf** [comment]
已经发布。
