### ISSUE TITLE
v4 版本存在于外部组件库中并引入当前项目后页面无法渲染

### ISSUE THREAD

**Issue by ItsRyanWu** [wechat-miniprogram/computed#53]
在项目源码中使用 v4 无问题，在我这边由 npm 管理的外部组件库中同样会使用 computed behavior。

经过一系列对比测试后发现，一旦当前小程序页面引用了来自 miniprogram_npm 的外部组件并且该组件使用了 computed behavior 时，页面无法渲染并且无任何报错信息。

在升级至 v4 之前一直用使用的 v2，升级之前各方面工作正常。

更新一：新增 v3 作为测试项后发现 v2, v3 均不会导致页面无法渲染，只有 v4 不正常

更新二：v3 虽然可以使页面渲染，但是页面内部的某个 setData 无法触发视图更新，无报错，未知原因。所以我还是退到了 v2，退回后一切正常。

总结：v2, v3, v4 各自有着自己的 bug，但 v2 最为稳定（除了无法 track 到另外的自定义 behavior 里面的 data）

**Comment by LastLeaf** [comment]
意思是 npm 间接引用时会导致页面无报错白屏？更换版本之后重新点击了开发者工具中的“构建 npm ”按钮了吗？

**Comment by ItsRyanWu** [comment]
> 意思是 npm 间接引用时会导致页面无报错白屏？更换版本之后重新点击了开发者工具中的“构建 npm ”按钮了吗？

1. 没错，可以理解为由于通过 npm 安装的组件引用了 v4 所以项目间接引用了 v4。但表现并非白屏，页面的背景色是可以渲染出来的，但是接下来的的进程应该是遇到了带有 v4 的 npm 组件所以渲染就停止了，甚至无法渲染页面本身内的组件。
2. 可以排除忘记重新构建 npm 的因素，因为该过程在我的项目里是集成在 npm script 中通过调用 CLI command 自动运行的，并且 debug 过程中也重启过构建脚本以及 devtool。可以排除人为操作上的失误原因。

**Comment by LastLeaf** [comment]
我自己尝试并没有问题， v4 可以被间接引用。

请注意检查一下 package.json 的 dependencies 中需要包含外部组件所在的 npm 项目。

如果找不到问题的话，方便把构建后的 miniprogram_npm 目录发出来我看看吗？（这个更像是 npm 构建时有问题而不是 computed 本身有问题。）

**Comment by TtTRz** [comment]
如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
