### ISSUE TITLE
v4: build npm 过程中 devtool 显示 warning: 未找到 @types/wechat-miniprogram/index.js

### ISSUE THREAD

**Issue by ItsRyanWu** [wechat-miniprogram/computed#54]
![image](https://user-images.githubusercontent.com/17338101/107347258-9772fe80-6b00-11eb-9f7c-d6cdb3279b77.png)

**Comment by LastLeaf** [comment]
已确认问题。

**Comment by LastLeaf** [comment]
已修复在 v4.0.3
