### ISSUE TITLE
TypeScript 开发，watch,onLoad 方法都无法使用this。

### ISSUE THREAD

**Issue by lfzm** [wechat-miniprogram/computed#55]
引用的包:
![image](https://user-images.githubusercontent.com/28291464/110735499-df528600-8264-11eb-94ee-2dd2083ec14f.png)

![image](https://user-images.githubusercontent.com/28291464/110735447-cd70e300-8264-11eb-9990-f5a90263e83e.png)

**Comment by LastLeaf** [comment]
tsconfig 的 noImplicitThis 选项需要被置为 true 才行。

**Comment by lfzm** [comment]
@LastLeaf 谢谢，已经找到解决方案了

**Comment by ouops** [comment]
> @LastLeaf 谢谢，已经找到解决方案了

请问您是如何 处理的。
