### ISSUE TITLE
同一组件(有计算属性)在不同页面渲染时,后渲染的组件会导致之前组件的计算属性失效。是不是缓存覆盖了？？

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/computed#56]
同一组件(有计算属性)在不同页面渲染时,后渲染的组件会导致之前组件的计算属性失效。是不是缓存覆盖了？？

**Comment by missannil** [comment]
代码片段  https://developers.weixin.qq.com/community/develop/doc/0004cc0454c190fafefbd13e85b400

**Comment by LastLeaf** [comment]
实现意图上，不同组件实例之间不应该有影响。

已经定位到一个 bug 。

**Comment by LastLeaf** [comment]
已在 v4.0.4 中修复。
