### ISSUE TITLE
watch一个计算属性，watch函数会在开始自动执行一次，是bug吗？

### ISSUE THREAD

**Issue by q2578443177** [wechat-miniprogram/computed#58]
watch非计算属性就不会有这种情况

**Comment by missannil** [comment]
计算属性的依赖是否有变动

**Comment by LastLeaf** [comment]
目前，计算属性会在 `attached` 期间被计算一次，然后触发监听器。

这个表现要改的话有点难度……影响大吗？

**Comment by TtTRz** [comment]
> watch非计算属性就不会有这种情况

修了一下，试试 `v4.1.2` 这个版本看能不能满足你的需求。

**Comment by q2578443177** [comment]
> > watch非计算属性就不会有这种情况
> 
> 修了一下，试试 `v4.1.2` 这个版本看能不能满足你的需求。

哈哈哈，小程序项目已经完工了。。。

**Comment by TtTRz** [comment]
> > > watch非计算属性就不会有这种情况
> > 
> > 
> > 修了一下，试试 `v4.1.2` 这个版本看能不能满足你的需求。
> 
> 哈哈哈，小程序项目已经完工了。。。

行，要是有问题再开 issue～
