### ISSUE TITLE
BUG: 对computed组件进行wx:for，多个item除了最后一个，其他item在data改变时，组件computed无效

### ISSUE THREAD

**Issue by weiyisheng** [wechat-miniprogram/computed#59]
**版本**："^4.0.3"；

**现象：** 对使用computed的组件进行wx:for生成列表，除了最后一个item，其他的item computed不会被调用到；

**初步探查原因：** 
` do {
            changed = computedWatchInfo.computedUpdaters.some(func => func.call(this));
          } while (changed);
    // func.call(this)不能改变箭头函数updateValueAndRelatedPaths的this指向，所以列表中所有组件的this总是指向最后一个item。
`

**我的分析：**  列表中的所有item共用了同一个computedWatchInfo（在definitionFilter中定义），所以每次添加一个item，updateValueAndRelatedPaths声明时，就绑定了新item作为this。

**Comment by LastLeaf** [comment]
并不是你找到的那个点的问题。那个位置是刻意用了箭头函数的。

怀疑与 #56 问题一致。麻烦更新到 4.0.4 试试？

**Comment by weiyisheng** [comment]
> 并不是你找到的那个点的问题。那个位置是刻意用了箭头函数的。
> 
> 怀疑与 #56 问题一致。麻烦更新到 4.0.4 试试？

升级到4.0.4，解决解决了
