### ISSUE TITLE
请问为什么计算属性不直接内置在基础库的核心能力中？

### ISSUE THREAD

**Issue by anrananran** [wechat-miniprogram/computed#6]
因为使用场景真的非常多啊

**Comment by JuneAndGreen** [comment]
现在基础库越来越庞大，我们的考虑是能以扩展方式的支持的尽量不内置到基础库中。

另外计算属性本身的规划是通过 observer 封装出来的能力，而目前基础库的 observer 能力仍在内部试行中仍未公开，一开始内置的话会存在变更困难，而开源出来的扩展可以通过安装不同的版本号处理。

另外 computed 本身也是自定义组件扩展的一个常见案例。

**Comment by anrananran** [comment]
了解，谢谢解答
