### ISSUE TITLE
4.0.4版本报错,Behaviors should be constructed with Behavior()

### ISSUE THREAD

**Issue by Typeve** [wechat-miniprogram/computed#60]
demo的版本是2.1.1是正常的
现在的版本4.0.4,编译页面会报错Behaviors should be constructed with Behavior()

**Comment by cnxfire** [comment]
我也碰到这个问题了

**Comment by cnxfire** [comment]
const computedBehavior = require('miniprogram-computed').behavior
这么写  问题解决

**Comment by Typeve** [comment]
> const computedBehavior = require('miniprogram-computed').behavior
> 这么写  问题解决

这不是示例写法吗？我直接复制的示例报错

**Comment by LastLeaf** [comment]
> const computedBehavior = require('miniprogram-computed').behavior
> 这么写 问题解决

在 >=4.0.0 时用这个写法。较低版本的话去掉末尾的 `.behavior` 。

这个是因为 4.0.0 改了接口。

**Comment by LastLeaf** [comment]
在文档里强调了这个问题。
