### ISSUE TITLE
behavior里面使用watch报错

### ISSUE THREAD

**Issue by tumblingG** [wechat-miniprogram/computed#61]
我在behavior里面使用了watch，然后合并到了组件中，此时报错
![image](https://user-images.githubusercontent.com/29335868/123615257-b4059e00-d837-11eb-8e56-0d2089431855.png)
这里的oldVal为undefined
![image](https://user-images.githubusercontent.com/29335868/123615375-d13a6c80-d837-11eb-9a5a-72686ede1229.png)

**Comment by LastLeaf** [comment]
请问用的版本是哪个呢？

**Comment by tumblingG** [comment]
"miniprogram-computed": "^3.1.0"

**Comment by tumblingG** [comment]
> 请问用的版本是哪个呢？

"miniprogram-computed": "^3.1.0"

**Comment by tumblingG** [comment]
> 请问用的版本是哪个呢？

"miniprogram-computed": "^3.1.0"
貌似在多层级的behavior中，watch的合并逻辑有问题

**Comment by LastLeaf** [comment]
分析了一下代码。有个直到 v4.0.4 才修复的 bug （#56），可能与你的 case 相关。尝试升级一下？

**Comment by TtTRz** [comment]
如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
