### ISSUE TITLE
Error: module "miniprogram_npm/miniprogram-computed/core-js/modules/esnext.weak-map.delete-all.js" is not defined

### ISSUE THREAD

**Issue by emoryH** [wechat-miniprogram/computed#63]
I get an error in the console when I use the latest version(4.0.5). It works fine when I remove the **.behavior** and change the version to 2.1.1.

![image](https://user-images.githubusercontent.com/89035011/130394644-64645457-aceb-444f-a858-503b2fe4b986.png)

![image](https://user-images.githubusercontent.com/89035011/130394014-1ab66e96-bc37-468b-92aa-119a7aa89b58.png)

**Comment by emoryH** [comment]
The problem still exists even if I upgrade Weixin Devtools to the latest version

![image](https://user-images.githubusercontent.com/89035011/130395299-51f581ee-7fdd-4e00-a42e-18ef60e1490f.png)

**Comment by TtTRz** [comment]
Would you please provide a demo that can reproduce this problem

**Comment by TtTRz** [comment]
Check the version of core-js. If it is lower than version 3.0, this problem may occur.

**Comment by emoryH** [comment]
> Would you please provide a demo that can reproduce this problem

https://developers.weixin.qq.com/s/iJUT1Lm77Zs9

or https://developers.weixin.qq.com/s/UqMytwmF7Gni  

The problem will be reproduced, change the version to 4.0.5.

**Comment by emoryH** [comment]
> Check the version of core-js. If it is lower than version 3.0, this problem may occur.

How to check core-js version? ：）

**Comment by TtTRz** [comment]
Fixed `ver: 4.0.6`.  It‘s a bug related to the babel & webpack . We plan to replace webpack & babel with esbuild & SWC soon.

**Comment by TtTRz** [comment]
> > Check the version of core-js. If it is lower than version 3.0, this problem may occur.
> 
> How to check core-js version?

Fixed ver: 4.0.6. It‘s a bug related to the babel & webpack . We plan to replace webpack & babel with esbuild & SWC soon.

**Comment by emoryH** [comment]
> > > Check the version of core-js. If it is lower than version 3.0, this problem may occur.
> > 
> > 
> > How to check core-js version?
> 
> Fixed ver: 4.0.6. It‘s a bug related to the babel & webpack . We plan to replace webpack & babel with esbuild & SWC soon.

@TtTRz When I upgraded the version to 4.0.6, it worked fine.

Thanks for your  code!

**Comment by TtTRz** [comment]
> > > > Check the version of core-js. If it is lower than version 3.0, this problem may occur.
> > > 
> > > 
> > > How to check core-js version?
> > 
> > 
> > Fixed ver: 4.0.6. It‘s a bug related to the babel & webpack . We plan to replace webpack & babel with esbuild & SWC soon.
> 
> @TtTRz When I upgraded the version to 4.0.6, it worked fine.
> 
> Thanks for your code!

I will close this issue.  :)

**Comment by Garfill** [comment]
It reproduced in version 4.1.3

**Comment by TtTRz** [comment]
> It reproduced in version 4.1.3

It looks good for me in version `4.1.3`.

Maybe you can try:
1. Check lib's version `^4.1.4` in `package.json`.
2. Reinstall `node_modules` and rebuild it.

Would you please provide a demo that can reproduce this problem.
