### ISSUE TITLE
created 的调用时机和官方叙述不一致

### ISSUE THREAD

**Issue by Hubmeat** [wechat-miniprogram/computed#64]
**为什么在 created 去 setData，官方明明说的 created 阶段不应该调用 setData 啊** 

![image](https://user-images.githubusercontent.com/25141100/131799965-6f1ed173-155b-42cb-a105-931c1c07ddb0.png)

![image](https://user-images.githubusercontent.com/25141100/131800832-3d00a909-9486-42ce-9a31-7a4aacaeebce.png)

**Comment by TtTRz** [comment]
> **为什么在 created 去 setData，官方明明说的 created 阶段不应该调用 setData 啊**
> 
> ![image](https://user-images.githubusercontent.com/25141100/131799965-6f1ed173-155b-42cb-a105-931c1c07ddb0.png)
> 
> ![image](https://user-images.githubusercontent.com/25141100/131800832-3d00a909-9486-42ce-9a31-7a4aacaeebce.png)

这里分开来解释：
1. 为什么文档中说 `created` 不能调用 `setData`
因为在 `created` 阶段的那个时刻去做 `setData`的话，data 并不会被渲染到页面上。（具体机制和小程序组件机制有关）
而 `setData` 主要的作用就是通知页面更新数据的，所以大多数情况下推荐在 `attached` 中使用 `setData`。

2. 为什么在 `created` 使用 `setData`
在 `created` 使用 `setData` 的主要目的是要触发 `observer`，从而调到一些逻辑（具体可以看代码）。
而通过 `this.data.xx = xxx` 并不会触发 `observer` 。

下面的代码片段可以研究下：
[https://developers.weixin.qq.com/s/zxaan1mx7Stk](https://developers.weixin.qq.com/s/zxaan1mx7Stk)
