### ISSUE TITLE
定义分享无效 onShareAppMessage

### ISSUE THREAD

**Issue by bosens-China** [wechat-miniprogram/computed#66]
``` js
ComponentWithComputed({
onShareAppMessage() {
}
})

```

**Comment by TtTRz** [comment]
> ```js
> ComponentWithComputed({
> onShareAppMessage() {
> }
> })
> ```

这是因为 `Component` 构造器下并没有 `onShareAppMessage`，该方法仅存在于 `Page` 构造器中。

目前来看，如果你需要使用此方法，可以用 `Page` 构造器创建页面并搭配 `BehaviorWithComputed` 使用。

还有一种方案是新增多一个 `PageWithComputed` 的 `API`，这里我仔细考虑下。

详情参考:
自定义组件: [https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html)
页面: [https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html)
