### ISSUE TITLE
fast-deep-equal和rfdc可以不写在dependencies里面吗？

### ISSUE THREAD

**Issue by echofly** [wechat-miniprogram/computed#67]
`fast-deep-equal`和`rfdc`可以不要写在`dependencies`里面吗？开发者工具npm构建的时候也会把这两个构建进去，但是这两个东西是无用的，因为miniprogram-computed已经有dist了

**Comment by TtTRz** [comment]
这两个依赖现在是 `external` 的，没有打到 `computed` 的 `dist` 里面。

**Comment by echofly** [comment]
好的，我还以为dist/index.js是可以直接使用的呢
