### ISSUE TITLE
请问如何传参进来呢

### ISSUE THREAD

**Issue by qiujunyu** [wechat-miniprogram/computed#68]
目前需求需要使用计算属性的时候用到传参

**Comment by TtTRz** [comment]
> 目前需求需要使用计算属性的时候用到传参

方便给一个使用例子吗

**Comment by TtTRz** [comment]
如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。

**Comment by qiujunyu** [comment]
> 如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
有个功能要对段落进行裁剪，所以要传入当前段落的内容，想过用wxs替换，但是需要用到小程序的api，可是wxs又没法调用小程序
的api。。

**Comment by qiujunyu** [comment]
> > > 如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
> > > 有个功能要对段落进行裁剪，所以要传入当前段落的内容，想过用wxs替换，但是需要用到小程序的api，可是wxs又没法调用小程序
> > > 的api。。
> 
> 我理解的是，你想要把段落 A 裁剪为段落 B，其中段落 B 是 computed 属性，然后你想要通过参数去控制 这个 computed 属性的计算结果？

是滴

**Comment by TtTRz** [comment]
> > > > 如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
> > > > 有个功能要对段落进行裁剪，所以要传入当前段落的内容，想过用wxs替换，但是需要用到小程序的api，可是wxs又没法调用小程序
> > > > 的api。。
> > 
> > 
> > 我理解的是，你想要把段落 A 裁剪为段落 B，其中段落 B 是 computed 属性，然后你想要通过参数去控制 这个 computed 属性的计算结果？
> 
> 是滴

对于这种情况 可以把参数放到 data 里面：在对应的计算属性里面拿到 data.xxx 作为参数去执行相应的逻辑

**Comment by qiujunyu** [comment]
> > > > > 如果无相关 case 的补充，该 issue 将在 24h 后关闭。若有追加问题，可重新打开此 Issue。
> > > > > 有个功能要对段落进行裁剪，所以要传入当前段落的内容，想过用wxs替换，但是需要用到小程序的api，可是wxs又没法调用小程序
> > > > > 的api。。
> > > 
> > > 
> > > 我理解的是，你想要把段落 A 裁剪为段落 B，其中段落 B 是 computed 属性，然后你想要通过参数去控制 这个 computed 属性的计算结果？
> > 
> > 
> > 是滴
> 
> 对于这种情况 可以把参数放到 data 里面：在对应的计算属性里面拿到 data.xxx 作为参数去执行相应的逻辑

可是这些段落都是循环渲染的，我现在改成直接在返回的数据里面去裁剪，然后再渲染
