### ISSUE TITLE
mobx-miniprogram 还维护吗？

### ISSUE THREAD

**Issue by weihongyu12** [wechat-miniprogram/computed#78]
mobx-miniprogram 这个包是基于 mobx 4，据文档而言是为了兼容 iOS 9。考虑到现在的使用环境的变化，有没有考虑升级 mobx 5？另外我想知道 mobx-miniprogram 还有没有后续的升级计划

**Comment by TtTRz** [comment]
有计划升级，后续会放出一个预览版进行测试

**Comment by TtTRz** [comment]
后续在 mobx-miniprogram 追踪
