### ISSUE TITLE
辅助组件构造器behavior注入位置不正确、配合MobX时TS类型存在缺陷

### ISSUE THREAD

**Issue by Wyatex** [wechat-miniprogram/computed#83]
如果配合官方的mobx-bindins一起用，会有个比较致命的问题：
- mobx-bindings通过behavior注入，那么再使用ComponentWithComputed进行构造，computedBehavior注入的位置在mobx-binding的behavior之前，导致第一次读取绑定的值是undefined。

而且ComponentWithComputed的computed读data读不到bingdings的类型，只能通过断言指定类型，看着比较膈应，不知道有没有更优雅的解决方式。

**Comment by TtTRz** [comment]
问题 1 已在 PR 中提出建议。
问题 2 有在调研相关优化。不过目前看来，在 computed 对 data 进行断言是最高效的方法，如果你有更好的提案也可以提出一起讨论看看。

**Comment by LastLeaf** [comment]
关闭不活跃的问题。
