### ISSUE TITLE
可以不通过npm构建，直接把dist目录里的文件放到项目里吗？

### ISSUE THREAD

**Issue by Youky1** [wechat-miniprogram/computed#88]

**Comment by TtTRz** [comment]
可以的

**Comment by Youky1** [comment]
> 可以的

我直接引用dist里的index.js后报错`'rfdc.js' is not defined, require args is 'rfdc'`，应该是有依赖其他库？

**Comment by Youky1** [comment]
> > 可以的
> 
> 我直接引用dist里的index.js后报错`'rfdc.js' is not defined, require args is 'rfdc'`，应该是有依赖其他库？

还有`fast-deep-equal`也是同理，我把这两个也放到本地就好了

**Comment by LastLeaf** [comment]
可以这样手工处理。
