### ISSUE TITLE
请问可以实现兼容app.globalData的监听吗？

### ISSUE THREAD

**Issue by shuimupj** [wechat-miniprogram/computed#91]
原生小程序没有状态管理 (Vuex和Redux)，只有一个globalData，很多页面共享的数据的都是存在globalData中的，但因为接口请求的异步，会导致globalData的数据会在页面加载完毕之后才有，所以请问一下watch的监听可以兼容监听app.globalData的变化嘛？🙏

**Comment by LastLeaf** [comment]
不应该把数据放在 app 里。全局数据直接单独放在独立的 js 里就好。

想要全局状态管理，可以用 MobX ：https://github.com/wechat-miniprogram/mobx-miniprogram-bindings 。
